# Generated by Django 3.2 on 2021-09-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('club', models.CharField(max_length=100)),
                ('course', models.TextField()),
                ('weather', models.TextField()),
                ('memory_details', models.TextField(max_length=5000)),
                ('date_amended', models.DateField()),
                ('is_current', models.BooleanField()),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
    ]
