# Generated by Django 3.2 on 2021-10-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_memory_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='shot_date',
            field=models.DateField(default='2021-10-01'),
            preserve_default=False,
        ),
    ]
